apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: client
  labels:
    name: client
    project: client
spec: {}
status: {}
---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: secure-network
  labels:
    name: secure-network
    project: secure-network
spec: {}
status: {}
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: curl-client-secure
    app: curl-client-secure
  name: curl-client-secure
  namespace: client
spec:
  containers:
  - command:
    - sleep
    - infinity
    image: curlimages/curl
    name: curl-client-secure
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: curl-client-blocked
    app: curl-client-blocked
  name: curl-client-blocked
  namespace: client
spec:
  containers:
  - command:
    - sleep
    - infinity
    image: curlimages/curl
    name: curl-client-blocked
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: echo-secure
    app: echo-secure
  name: echo-secure
  namespace: secure-network
spec:
  containers:
  - image: k8s.gcr.io/echoserver:1.10
    name: echo-secure
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: curl-secure
    app: curl-secure
  name: curl-secure
  namespace: secure-network
spec:
  containers:
  - command:
    - sleep
    - infinity
    image: curlimages/curl
    name: curl-secure
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: curl-blocked
    app: curl-blocked
  name: curl-blocked
  namespace: secure-network
spec:
  containers:
  - command:
    - sleep
    - infinity
    image: curlimages/curl
    name: curl-blocked
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
