apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: net-pol-for-multiple-pods
  namespace: secure-network
spec:
  podSelector:
    matchLabels:
      app: echo-secure
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: curl-secure
    - podSelector:
        matchLabels:
          app: curl-blocked
    ports:
    - protocol: TCP
      port: 8080
