apiVersion: v1
kind: PersistentVolume
metadata:
  name: share1
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  nfs:
    path: /nfs/share1
    server: 192.168.180.130
    readOnly: false
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: share2
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  nfs:
    path: /nfs/share2
    server: 192.168.180.130
    readOnly: false
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: share3
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  nfs:
    path: /nfs/share3
    server: 192.168.180.130
    readOnly: false
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: share4
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: dynamic
  nfs:
    path: /nfs/share4
    server: 192.168.180.130
    readOnly: false
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: share5
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: dynamic
  nfs:
    path: /nfs/share5
    server: 192.168.180.130
    readOnly: false
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: share6
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: dynamic
  nfs:
    path: /nfs/share6
    server: 192.168.180.130
    readOnly: false
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: share7
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: fast
  nfs:
    path: /nfs/share7
    server: 192.168.180.130
    readOnly: false
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: share8
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: fast
  nfs:
    path: /nfs/share8
    server: 192.168.180.130
    readOnly: false
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: share9
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: fast
  nfs:
    path: /nfs/share3
    server: 192.168.180.130
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: share1
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: slow
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: share2
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: slow
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: share3
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: slow
